version: '3.8'

services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ao-tech.co.uk/api
    ports:
      - "8080:80"
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - DB_HOST=194.164.91.42  # ✅ change this if DB is a container
      - DB_USER=andrei
      - DB_PASSWORD=Romania1989!
      - DB_NAME=cruddatabase
      - DB_PORT=3307
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./server:/usr/src/app
    command: sh -c "node index.js"

networks:
  app-network:
    driver: bridge
