name: Deploy Full Stack App (Frontend + Backend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Upload project to server
      run: |
        rsync -avz --exclude=node_modules --exclude=build . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/ao-tech

    - name: Deploy backend and frontend on server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/${{ secrets.SERVER_USER }}/ao-tech

          # Rebuild backend container
          cd backend
          docker stop backend || true && docker rm backend || true
          docker build -t ao-tech-backend .
          docker run -d --name backend -p 3001:3001 ao-tech-backend
          cd ..

          # Rebuild frontend container
          cd client
          docker stop frontend || true && docker rm frontend || true
          docker build -t ao-tech-frontend --build-arg REACT_APP_API_URL=https://ao-tech.co.uk/api .
          docker run -d --name frontend -p 80:80 ao-tech-frontend
          cd ..
        EOF
